# Generated by Django 6.0 on 2026-01-17 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='users.channel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название видео'),
        ),
    ]
