# Generated by Django 6.0 on 2026-01-19 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videos_preview_alter_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='preview',
            field=models.ImageField(blank=True, upload_to='Channels/PreviewVideo/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(max_length=1000, upload_to='Channels/Video/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
    ]
