# Generated by Django 6.0 on 2026-01-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='playvid/Channels/AvatarChannel/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='preview',
            field=models.ImageField(blank=True, upload_to='playvid/Channels/PreviewsChannel/%Y/%m/%d/'),
        ),
    ]
